// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OperacionTupper2._0.Data;

#nullable disable

namespace OperacionTupper2._0.Migrations
{
    [DbContext(typeof(OperacionTupperContext))]
    [Migration("20251102162652_InitEsquemaMenus")]
    partial class InitEsquemaMenus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OperacionTupper2._0.Models.Ingrediente", b =>
                {
                    b.Property<int>("IdIngrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIngrediente"));

                    b.Property<string>("NombreIngrediente")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdIngrediente");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("OperacionTupper2._0.Models.Menu", b =>
                {
                    b.Property<int>("IdMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMenu"));

                    b.Property<int>("DiasMenu")
                        .HasColumnType("int");

                    b.Property<string>("NombreMenu")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdMenu");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("OperacionTupper2._0.Models.MenuDetalle", b =>
                {
                    b.Property<int>("IdMenuDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMenuDetalle"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<int>("HoraComida")
                        .HasColumnType("int");

                    b.Property<int>("IdMenu")
                        .HasColumnType("int");

                    b.Property<int>("IdPlato")
                        .HasColumnType("int");

                    b.Property<int>("MenuIdMenu")
                        .HasColumnType("int");

                    b.Property<int>("PlatoIdPlato")
                        .HasColumnType("int");

                    b.HasKey("IdMenuDetalle");

                    b.HasIndex("MenuIdMenu");

                    b.HasIndex("PlatoIdPlato");

                    b.HasIndex("IdMenu", "DiaSemana", "HoraComida")
                        .IsUnique();

                    b.ToTable("MenusDetalles");
                });

            modelBuilder.Entity("OperacionTupper2._0.Models.Plato", b =>
                {
                    b.Property<int>("IdPlato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlato"));

                    b.Property<int>("AcompanamientoPrincipal")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GrupoNutricional")
                        .HasColumnType("int");

                    b.Property<int>("HoraComida")
                        .HasColumnType("int");

                    b.Property<string>("NombrePlato")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PlatoUnico")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("IdPlato");

                    b.ToTable("Platos");
                });

            modelBuilder.Entity("OperacionTupper2._0.Models.PlatoIngrediente", b =>
                {
                    b.Property<int>("IdPlatoIngrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlatoIngrediente"));

                    b.Property<int>("IdIngrediente")
                        .HasColumnType("int");

                    b.Property<int>("IdPlato")
                        .HasColumnType("int");

                    b.HasKey("IdPlatoIngrediente");

                    b.HasIndex("IdIngrediente");

                    b.HasIndex("IdPlato");

                    b.ToTable("PlatoIngredientes");
                });

            modelBuilder.Entity("OperacionTupper2._0.Models.MenuDetalle", b =>
                {
                    b.HasOne("OperacionTupper2._0.Models.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuIdMenu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperacionTupper2._0.Models.Plato", "Plato")
                        .WithMany()
                        .HasForeignKey("PlatoIdPlato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Plato");
                });

            modelBuilder.Entity("OperacionTupper2._0.Models.PlatoIngrediente", b =>
                {
                    b.HasOne("OperacionTupper2._0.Models.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IdIngrediente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperacionTupper2._0.Models.Plato", "Plato")
                        .WithMany()
                        .HasForeignKey("IdPlato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Plato");
                });
#pragma warning restore 612, 618
        }
    }
}
